In [1]:
import numpy as np

In [8]:
lista_python = [1,2,3,4,5,6,7]
lista_python


[1, 2, 3, 4, 5, 6, 7]

In [9]:
type(lista_python)

list

In [6]:
array_np = np.array(lista_python)
array_np

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
type(array_np)

numpy.ndarray

In [11]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Indexing --> entrar en una estructura.

In [12]:
array_np

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
array_np[1]

2

In [14]:
array_np[0] + array_np[4]

6

In [15]:
# Matrix --> su indice es [filas, columnas]

In [16]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
matrix[0]

array([1, 2, 3])

In [18]:
matrix[1,2]

6

In [19]:
# Slacing in vectors

array_np

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
array_np[0:4]

array([1, 2, 3, 4])

In [21]:
array_np[:5]

array([1, 2, 3, 4, 5])

In [22]:
array_np[2:]

array([3, 4, 5, 6, 7])

In [23]:
array_np[::3]

array([1, 4, 7])

In [24]:
array_np[-3::]

array([5, 6, 7])

In [25]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrix[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [27]:
matrix[1:,0:2]

array([[4, 5],
       [7, 8]])