In [12]:
import numpy as np

In [13]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
arr.dtype

dtype('int32')

In [15]:
arr = np.array([1,2,3,4], dtype='float64')
print(arr)
arr.dtype

[1. 2. 3. 4.]


dtype('float64')

In [16]:
arr2 = np.array([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [18]:
arr2 = arr2.astype(np.float64)
arr2

array([1., 2., 3., 4.])

In [20]:
arr = np.array([0,1,2,3,4])
print(arr)
arr = arr.astype(np.bool_)
arr

[0 1 2 3 4]


array([False,  True,  True,  True,  True])

In [21]:
arr = np.array([0,1,2,3,4])
print(arr)
arr = arr.astype(np.string_)
arr

[0 1 2 3 4]


array([b'0', b'1', b'2', b'3', b'4'], dtype='|S11')