In [1]:
import numpy as np

Para saber el número de dimensiones usamos el objeto .ndim

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [5]:
vector = np.array([1,2,3,4,5])
print(vector)
vector.ndim

[1 2 3 4 5]


1

In [6]:
matrix = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(matrix)
matrix.ndim

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


2

In [7]:
tensor = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])
print(tensor)
tensor.ndim

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


3

Agregar o Eliminar Dimensiones

In [9]:
# Así agregamos dimensiones a cualquier array

vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [11]:
# Para expandir dimensiones se usa expand_dims. If axis = 0: Expande Filas. If axis = 1: Expande Columnas

expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [13]:
# Para comprimir una estructura a su dimensionalidad correcta, usamos np.squeeze

print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
