In [2]:
import numpy as np

Para saber cuantas filas y columnas tenemos usamos: .shape

In [7]:
arr = np.random.randint(1,40, (3, 2))

print(arr)
arr.shape

[[18  5]
 [ 5 24]
 [24 22]]


(3, 2)

Para cambiar la estructura en la que se agrupan los datos usamos: .reshape

In [5]:
arr.reshape(1, 6)

array([[26, 16, 13, 24,  8, 35]])

In [6]:
arr.reshape(2, 3)

array([[26, 16, 13],
       [24,  8, 35]])

In [8]:
# Otra forma de hacer esta funcionalidad:

np.reshape(arr, (1, 6))

array([[18,  5,  5, 24, 24, 22]])

Podemos ordenar las estructuras cómo los lenguajes 'C' o 'Fortran'

In [11]:
# Ordenado cómo lenguaje C
np.reshape(arr, (2, 3), 'C')

array([[18,  5,  5],
       [24, 24, 22]])

In [12]:
# Ordenado cómo lenguaje Fortran
np.reshape(arr, (2, 3), 'F')

array([[18, 24, 24],
       [ 5,  5, 22]])

In [14]:
# Ordenado según la optimización de mi sistema
np.reshape(arr, (2, 3), 'A')

array([[18,  5,  5],
       [24, 24, 22]])