In [104]:
import numpy as np

In [105]:
list_python = list(range(0, 10))

list_python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [106]:
array_numpy = np.arange(0, 10)

array_numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
array_zeros = np.zeros(5)

array_zeros

array([0., 0., 0., 0., 0.])

In [108]:
array_zeros_more_dimentions = np.zeros((10, 10))

array_zeros_more_dimentions

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [109]:
array_ones = np.ones((10, 5))

array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [110]:
normalized_distribution = np.linspace(0, 20, 100)

normalized_distribution

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [111]:
identity_matrix = np.eye(5)

identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [112]:
random_value_scalar_betwen_zero_one = np.random.rand()

random_value_scalar_betwen_zero_one

0.5550353107177936

In [113]:
random_value_vector_betwen_zero_one = np.random.rand(4)

random_value_vector_betwen_zero_one

array([0.68950674, 0.33475315, 0.88054052, 0.53884731])

In [114]:
random_value_matrix_betwen_zero_one = np.random.rand(4, 4)

random_value_matrix_betwen_zero_one

array([[0.19143432, 0.44458722, 0.95972803, 0.73125817],
       [0.80594781, 0.88685584, 0.35096253, 0.44589897],
       [0.12940989, 0.98570607, 0.27338722, 0.03505897],
       [0.1768956 , 0.15026013, 0.00949212, 0.81836638]])

In [115]:
random_value_int_scalar = np.random.randint(0, 20)

random_value_int_scalar

16

In [116]:
random_value_int_vector = np.random.randint(0, 100, (10))

random_value_int_vector

array([50, 16, 74, 97, 61, 66, 61,  3, 70, 73])

In [117]:
random_value_int_matrix = np.random.randint(0, 25, (10, 10))

random_value_int_matrix

array([[ 7, 21, 15, 14,  3,  2,  2, 13, 17, 18],
       [14, 19, 16,  3, 17, 22, 12, 15, 23, 17],
       [10, 22, 24, 12, 14, 20, 14,  5,  8, 23],
       [12,  1,  8,  1,  2, 23, 12,  1, 19,  9],
       [ 0, 17, 20,  6, 14,  9, 17, 16, 14,  9],
       [ 3,  3,  1,  7, 10,  0,  5,  3, 12,  2],
       [10, 18, 13,  4, 18, 14, 14, 21,  5,  7],
       [ 7, 19, 14, 16,  5,  0, 21,  5, 16, 10],
       [24,  2, 20, 23,  2,  5, 13,  6,  6,  8],
       [ 0, 19,  7, 16, 24, 10,  3, 24, 15,  1]])